Iss 057
josephburnett/jd pull request #63
Opened 2024-02-07 13:29 UTC by adatoo

@josephburnett 

I had the same need to include a parameter for precision. I have updated the code to support this feature.

Some notes:

* I noticed one bug (I think) in `diff_common.go` where metadata was not being passed through.
* Precision is passed as a float64 flag which appears to provide the most flexibility in precision
* I have updated the code (against v 1.7) and marked as version 1.8.

Please reach out if you would like me to make any changes or need clarification.

Thanks for the amazing utility.

2024-02-10 18:58 UTC, josephburnett requested changes
This is great! Metadata is a nice way to plumb this through. Just one request to drop a commit and retarget master.

I've been dragging my heels on adding precision (and a few other things) because I'm working on a 2.0 format in order to implement [Smallest Edit Distance](https://github.com/josephburnett/jd/issues/50). Most new features will come in 2.0 and the 1.0 (`lib`) branch will be in maintenance mode.

But since a couple people have expressed interest in this, I'm happy to accept it. And I'll reimplement in 2.0.

Thanks for the contribution!

2024-02-10 18:58 UTC, josephburnett commented on main.go
> +const version = "1.8.0"
Please remove this change. And make your merge request target `master`. All new changes land there first. Then I'll cut a new release branch and build new binaries. You have the number right; I'll release version `1.8.0` but I won't backport this feature to the 0.7 release branch. That's just for critical bug fixes. Thanks!!

2024-02-10 20:45 UTC, adatoo commented
Happy to do these changes. However, I have a question:

It appears that the master is targetting the v2 release - for example, in `main.go` the import statement on line 12 is importing the `jd` package from the `v2` folder as opposed to the `lib` folder. Also in `main.go`,  the parseMetadata function is using the new Option type which replaces the Metadata type in your v1 release. However the v2 folder still seems to have the Metadata type defined.

My confusion is that I rebase the changes on `master`, do I need to make my changes against the code in the `v2` folder as opposed to the `lib` folder?

2024-02-11 07:35 UTC, josephburnett commented
I thought that v2 was ready for prime time. But I've encountered a few bugs, fixed in another branch. So I'm going to put it behind a flag, defaulting to `false`. Your changes against `lib` are fine. The ones in `main.go` might need to wait until I change back to v1. 

If you wouldn't mind, will you update the pull request with just the `lib` changes, which should rebase cleanly. Then I'll update `main.go` and we can add the flag then. Should be just a day or two.

2024-02-11 19:22 UTC, closed without merging