Read* to accept an []byte
josephburnett/jd pull request #87
Opened 2024-11-14 18:06 UTC by raphaelfff

2024-11-16 11:02 UTC, ccoVeille requested changes

2024-11-16 11:02 UTC, ccoVeille commented on v2/node_read.go
>  func ReadYamlString(s string) (JsonNode, error) {
```suggestion
// ReadYamlString reads a string as YAML and constructs a JsonNode.
func ReadYamlString(s string) (JsonNode, error) {
```

Please note, I'm aware, you didn't update this line. But there is a problem with it, so I'm reporting it

2024-11-16 11:02 UTC, ccoVeille commented on v2/node_read.go
> +func ReadYamlBytes(s []byte) (JsonNode, error) {
```suggestion
// ReadYamlBytes reads a []byte as YAML and constructs a JsonNode.
func ReadYamlBytes(s []byte) (JsonNode, error) {
```

2025-02-10 03:47 UTC, josephburnett commented
@raphaelfff thank you for the pull request. Can you tell me more about why you need this conversion function? Previously I have decided not to add these functions because Go already provides an easy way to convert: https://github.com/josephburnett/jd/pull/56. But I'm open to changing my mind 🙏

2025-02-15 04:14 UTC, josephburnett commented
> @raphaelfff thank you for the pull request. Can you tell me more about why you need this conversion function? Previously I have decided not to add these functions because Go already provides an easy way to convert: #56. But I'm open to changing my mind 🙏

I'm going to close this for now. If you think you have a convincing reason why we need this, given the context I added, feel free to reopen it.

2025-02-15 04:14 UTC, closed without merging